quina/config/routes.rb
Quina::Application.routes.draw do

  resources :bilhetes

  root to:'home#index'

  post 'resultado' => 'home#resultado'

  post 'salvar_dados_na_session' => 'home#salvar_dados_na_session'
  

end

quina/app/models/bilhete.rb
class Bilhete < ActiveRecord::Base
  attr_accessible :concurso_final, :concurso_inicial, :tipo, :usuario, :jogos_attributes

  has_many :jogos
  has_many :numeros, through: :jogos

  accepts_nested_attributes_for :jogos

end

quina/app/models/jogo.rb
class Jogo < ActiveRecord::Base

  attr_accessible :bilhete_id, :numeros_attributes

  belongs_to :bilhete
  has_many :numeros

  accepts_nested_attributes_for :numeros
end

quina/app/models/numero.rb
class Numero < ActiveRecord::Base
  belongs_to :jogo
  attr_accessible :numero, :jogo_id

end

quina/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

quina/app/controllers/bilhetes_controller.rb
class BilhetesController < ApplicationController
  # GET /bilhetes
  # GET /bilhetes.json
  def index
    @bilhetes = Bilhete.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bilhetes }
    end
  end

  # GET /bilhetes/1
  # GET /bilhetes/1.json
  def show
    @bilhete = Bilhete.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bilhete }
    end
  end

  # GET /bilhetes/new
  # GET /bilhetes/new.json
  def new
    @bilhete = Bilhete.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bilhete }
    end
  end

  # GET /bilhetes/1/edit
  def edit
    @bilhete = Bilhete.find(params[:id])
  end

  # POST /bilhetes
  # POST /bilhetes.json
  def create
    @bilhete = Bilhete.new(params[:bilhete])

    respond_to do |format|
      if @bilhete.save
        format.html { redirect_to @bilhete, notice: 'Bilhete was successfully created.' }
        format.json { render json: @bilhete, status: :created, location: @bilhete }
      else
        format.html { render action: "new" }
        format.json { render json: @bilhete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bilhetes/1
  # PUT /bilhetes/1.json
  def update
    @bilhete = Bilhete.find(params[:id])

    respond_to do |format|
      if @bilhete.update_attributes(params[:bilhete])
        format.html { redirect_to @bilhete, notice: 'Bilhete was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bilhete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bilhetes/1
  # DELETE /bilhetes/1.json
  def destroy
    @bilhete = Bilhete.find(params[:id])
    @bilhete.destroy

    respond_to do |format|
      format.html { redirect_to bilhetes_url }
      format.json { head :no_content }
    end
  end
end

quina/app/controllers/home_controller.rb
# encoding: utf-8
class HomeController < ApplicationController
  def index
    agent = Mechanize.new
    page = agent.get("http://www1.caixa.gov.br/loterias/loterias/quina/quina_pesquisa_new.asp?")
    @ultimo_concurso = page.search("body").text[0..3].to_i
  end

  def salvar_dados_na_session
    session[params["atributo"]] = params["valor"]
    render :nothing => true
  end

  def resultado

    session[:concurso_inicio] = params[:concurso_inicio]
    session[:concurso_fim] = params[:concurso_fim]

    jogos = []
    
    @resultados = []

    ('a'..'d').each do |l|
      jogo = []
      (1..5).each do |n|
        session["n#{l}#{n}"] = params["n#{l}#{n}"]
        jogo << params["n#{l}#{n}"].to_i
      end
      jogos << jogo 
    end

    agent = Mechanize.new

    (params[:concurso_inicio]..params[:concurso_fim]).each do |concurso|

      page = agent.get("http://www1.caixa.gov.br/loterias/loterias/quina/quina_pesquisa_new.asp?submeteu=sim&opcao=concurso&txtConcurso=#{concurso}")

      sorteados = page.search("span#sorteio2>ul>li").map {|x| x.text.to_i}

      jogos.each do |jogo|
        acertos = []
        jogo.each do |numero|
          acertos << numero if sorteados.include?(numero)
        end
        if acertos.empty?
          @resultados << "Concurso: #{concurso}. Você não acertou nenhum número. Os números sorteados foram: #{sorteados.join(', ')}."
        elsif acertos.size == 1
          @resultados << "Concurso: #{concurso}. Você só acertou o número #{acertos[0]}. Os números sorteados foram: #{sorteados.join(', ')}." 
        else
          @resultados << "Concurso: #{concurso}. Você acertou os números: #{acertos.join(', ')}. Os números sorteados foram: #{sorteados.join(', ')}."
        end
      end
    end
  end
end

quina/app/helpers/application_helper.rb
module ApplicationHelper
end

quina/app/helpers/bilhetes_helper.rb
module BilhetesHelper
end

quina/app/helpers/home_helper.rb
module HomeHelper
end

quina/app/views/bilhetes/_form.html.erb
<%= form_for(@bilhete) do |f| %>
  <% if @bilhete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bilhete.errors.count, "error") %> prohibited this bilhete from being saved:</h2>

      <ul>
      <% @bilhete.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :concurso_inicial %><br />
    <%= f.number_field :concurso_inicial %>
  </div>
  <div class="field">
    <%= f.label :concurso_final %><br />
    <%= f.number_field :concurso_final %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :jogos %><br/><br/>
    <%= f.fields_for :jogos do |jogo| %>
      <%= jogo.fields_for :numeros do |numero| %>
        <%= numero.text_field "numero", size:1, maxlength:2 %>
      <% end %>  <%= link_to "Adicionar número" %>
      <hr/>
    <% end %>
    <%= link_to "Adicionar jogo" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

quina/app/views/bilhetes/edit.html.erb
<h1>Editing bilhete</h1>

<%= render 'form' %>

<%= link_to 'Show', @bilhete %> |
<%= link_to 'Back', bilhetes_path %>

quina/app/views/bilhetes/index.html.erb
<h1>Listing bilhetes</h1>

<table>
  <tr>
    <th>Usuario</th>
    <th>Tipo</th>
    <th>Concurso inicial</th>
    <th>Concurso final</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bilhetes.each do |bilhete| %>
  <tr>
    <td><%= bilhete.usuario %></td>
    <td><%= bilhete.tipo %></td>
    <td><%= bilhete.concurso_inicial %></td>
    <td><%= bilhete.concurso_final %></td>
    <td><%= link_to 'Show', bilhete %></td>
    <td><%= link_to 'Edit', edit_bilhete_path(bilhete) %></td>
    <td><%= link_to 'Destroy', bilhete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bilhete', new_bilhete_path %>

quina/app/views/bilhetes/new.html.erb
<h1>New bilhete</h1>

<%= render 'form' %>

<%= link_to 'Back', bilhetes_path %>

quina/app/views/bilhetes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuario:</b>
  <%= @bilhete.usuario %>
</p>

<p>
  <b>Tipo:</b>
  <%= @bilhete.tipo %>
</p>

<p>
  <b>Concurso inicial:</b>
  <%= @bilhete.concurso_inicial %>
</p>

<p>
  <b>Concurso final:</b>
  <%= @bilhete.concurso_final %>
</p>


<%= link_to 'Edit', edit_bilhete_path(@bilhete) %> |
<%= link_to 'Back', bilhetes_path %>

quina/app/views/home/index.html.erb
<%= form_tag 'resultado' do %>
  <h1>Jogou na Quina? Deixe que eu vejo se você ganhou!</h1>
  <p>Último concurso: <%= @ultimo_concurso %></p>
  <p>
    Concurso inicial: <%= text_field_tag :concurso_inicio, session[:concurso_inicio], size:4, maxlength:5, onblur: "save_on_session(this);"%>
  </p>
  <p>
    Concurso final: <%= text_field_tag :concurso_fim, session[:concurso_fim], size:4, maxlength:5, onblur: "save_on_session(this);" %>
  </p>

  <p>Jogo:
   <%= text_field_tag :na1, session["na1"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :na2, session["na2"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :na3, session["na3"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :na4, session["na4"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :na5, session["na5"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
  </p>
  <p>Jogo:
   <%= text_field_tag :nb1, session["nb1"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :nb2, session["nb2"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :nb3, session["nb3"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :nb4, session["nb4"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :nb5, session["nb5"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
  </p>
  <p>Jogo:
   <%= text_field_tag :nc1, session["nc1"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :nc2, session["nc2"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :nc3, session["nc3"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :nc4, session["nc4"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :nc5, session["nc5"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
  </p>
  <p>Jogo:
   <%= text_field_tag :nd1, session["nd1"] , size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :nd2, session["nd2"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :nd3, session["nd3"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :nd4, session["nd4"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
   <%= text_field_tag :nd5, session["nd5"], size:1, maxlength:2, onblur: "save_on_session(this);" %>
  </p>
  <%= submit_tag 'Verificar' %> Atenção: a consulta pode demorar!
<% end %>

<script>
  function save_on_session(attr) {
    $.post("/salvar_dados_na_session", {atributo:attr.id, valor:attr.value});
  }
</script>

quina/app/views/home/resultado.html.erb
<% @resultados.each do |resultado| %>
  <p><%= resultado %></p>
<% end %>

quina/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quina</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>